### ISSUE TITLE
what py ver should i use and why i get error?

### ISSUE THREAD

**Issue by jamieduk** [yoanncouillec/Rsa#3]
jay@jnet:~/Documents/Scripts/Crypto/Crypto-Chat/PyRSA$ ./test2.py rsa
Traceback (most recent call last):
  File "./test2.py", line 23, in <module>
    class Rsa:
  File "./test2.py", line 209, in Rsa
    if generate_rsa_keys:
NameError: name 'generate_rsa_keys' is not defined

tried using py2 and 3 and get error!

**Comment by yoanncouillec** [comment]
Hello Jamie,
Thanks for the feedback.
I check that today.
Cheers
Yoann
